modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "https://github.com/GlovesRidge/LearningForge/issues"

[[mods]]
modId = "learningforge"
version = "${version}"
displayName = "Learning Forge"
updateJSONURL = "http://myurl.me/"
displayURL = "https://github.com/GlovesRidge/LearningForge"
logoFile = "examplemod.png"
credits = "Thank you God for giving me the strength to keep going"
authors = "Gloves Ridge <gloves.ridge@gmail.com>"
description = "A mod for Minecraft that was created as a learning project based on Cadiboo's tutorials (https://cadiboo.github.io/)."

[[dependencies.learningforge]]
modId = "forge"
mandatory = true
versionRange = "[31,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.learningforge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "NONE"
side = "BOTH"
